// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

/**
 * @title RejectingMockVerifier
 * @notice Test-only verifier that ALWAYS returns false.
 *
 *         Used by the JS test suite to exercise the InvalidProof revert path
 *         in VotingContract.castVote without depending on the real (placeholder)
 *         Verifier.sol — keeping the test independent from how the real verifier
 *         is generated by SnarkJS.
 *
 *         NEVER deploy this on a public network.
 */
contract RejectingMockVerifier {
    function verifyProof(
        bytes memory /* _proof */,
        uint256[] memory /* _pubSignals */
    ) external pure returns (bool) {
        return false;
    }
}
