// SPDX-License-Identifier: MIT
// This file is a placeholder for the Verifier contract generated by SnarkJS.
// It will be replaced by the actual verifier generated from the ZK circuit repository.
pragma solidity ^0.8.20;

/**
 * @title IVerifier
 * @notice Interface for the SnarkJS-generated PLONK Verifier.
 *         The signature matches the output of `snarkjs plonk export solidityverifier`.
 */
interface IVerifier {
    function verifyProof(
        bytes memory _proof,
        uint256[] memory _pubSignals
    ) external view returns (bool);
}

/**
 * @title Verifier
 * @notice Placeholder PLONK verifier. Replace with the Verifier.sol generated by
 *         SnarkJS in the ZK circuit repository (votacao-zk-circuits).
 *
 * Public signals layout (must match voter_proof.circom):
 *   _pubSignals[0] — merkle_root    (voter Merkle tree root)
 *   _pubSignals[1] — nullifier_hash (anti-double-vote commitment)
 *   _pubSignals[2] — candidate_id   (0 = blank, 999 = null, or sequential candidate ID)
 *   _pubSignals[3] — election_id    (unique election identifier)
 */
contract Verifier {
    /**
     * @dev Always returns false so that tests using the real verifier fail clearly.
     *      Unit tests should deploy a MockVerifier instead of this contract.
     */
    function verifyProof(
        bytes memory,    /* _proof */
        uint256[] memory /* _pubSignals */
    ) external pure returns (bool) {
        return false;
    }
}
