// SPDX-License-Identifier: MIT
// This file is a placeholder for the Verifier contract generated by SnarkJS.
// It will be replaced by the actual verifier generated from the ZK circuit repository.
pragma solidity ^0.8.20;

/**
 * @title IVerifier
 * @notice Interface for the SnarkJS-generated PLONK Verifier.
 *         The signature matches the output of `snarkjs plonk export solidityverifier`.
 *
 * Public signals layout (canonical definition — referenced by all other contracts):
 *   _pubSignals[0] — merkle_root    (voter Merkle tree root)
 *   _pubSignals[1] — nullifier_hash (Poseidon(voter_id, election_id, race_id))
 *   _pubSignals[2] — candidate_id   (0 = blank, 999 = null, or sequential candidate ID)
 *   _pubSignals[3] — election_id    (unique election identifier)
 *   _pubSignals[4] — race_id        (cargo identifier — PUBLIC signal, prevents cross-race
 *                                    proof reuse by a malicious relayer)
 *
 * @dev `verifyProof` is intentionally NOT marked `view` so that:
 *   (a) VotingContract calls it with CALL (not STATICCALL), and
 *   (b) MockVerifier can write state (lastProof, lastPubSignals) for test inspection.
 *   The real snarkjs-generated verifier is still compatible — `pure`/`view`
 *   functions can always be invoked via CALL without side-effects.
 */
interface IVerifier {
    function verifyProof(
        bytes memory _proof,
        uint256[] memory _pubSignals
    ) external returns (bool);
}

/**
 * @title Verifier
 * @notice Placeholder PLONK verifier. Replace with the Verifier.sol generated by
 *         SnarkJS in the ZK circuit repository (votacao-zk-circuits).
 *
 * @dev Always returns false so that tests using the real verifier fail clearly.
 *      Deploy a MockVerifier instead for unit tests.
 */
contract Verifier {
    function verifyProof(
        bytes memory,    /* _proof */
        uint256[] memory /* _pubSignals */
    ) external pure returns (bool) {
        return false;
    }
}
