// SPDX-License-Identifier: MIT
// This file is a placeholder for the Verifier contract generated by SnarkJS.
// It will be replaced by the actual verifier generated from the ZK circuit repository.
pragma solidity ^0.8.20;

/**
 * @title IVerifier
 * @notice Interface that the SnarkJS-generated Verifier must implement.
 */
interface IVerifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[2] calldata _pubSignals
    ) external view returns (bool);
}

/**
 * @title Verifier
 * @notice Placeholder Groth16 verifier. Replace with the SnarkJS-generated verifier.
 *
 * Public signals layout (must match the ZK circuit):
 *   _pubSignals[0] — nullifier hash
 *   _pubSignals[1] — candidate ID (0 = blank vote, type(uint256).max = null vote)
 */
contract Verifier {
    /**
     * @dev Always returns false so that tests that use the real verifier fail clearly.
     *      Unit tests should deploy a MockVerifier instead of this contract.
     */
    function verifyProof(
        uint[2] calldata, /* _pA */
        uint[2][2] calldata, /* _pB */
        uint[2] calldata, /* _pC */
        uint[2] calldata /* _pubSignals */
    ) external pure returns (bool) {
        return false;
    }
}
