/**
 * interact.js — Example interaction script for VotingContract.
 *
 * Usage:
 *   VOTING_ADDRESS=0x... VERIFIER_ADDRESS=0x... npx hardhat run scripts/interact.js --network sepolia
 *
 * The script demonstrates the full lifecycle of an election:
 *   1. createElection
 *   2. addCandidate (×2)
 *   3. registerVoterHashes
 *   4. setMerkleRoot
 *   5. openElection
 *   6. getZeresima (confirm zero votes)
 *   7. castVote  (with a placeholder PLONK proof — replace with a real proof in production)
 *   8. closeElection
 *   9. getResults
 */

import hre from "hardhat";
const { ethers } = hre;

// ─── Configuration ────────────────────────────────────────────────────────────
const VOTING_ADDRESS = process.env.VOTING_ADDRESS;
const VERIFIER_ADDRESS = process.env.VERIFIER_ADDRESS;

if (!VOTING_ADDRESS || !VERIFIER_ADDRESS) {
  throw new Error(
    "Please set VOTING_ADDRESS and VERIFIER_ADDRESS environment variables."
  );
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Build a dummy PLONK proof accepted by MockVerifier only.
 * Replace with a real proof generated by snarkjs in production.
 *
 * @param merkleRoot  Voter Merkle root stored in the contract
 * @param nullifier   Nullifier hash (prevents double voting)
 * @param candidateId Candidate ID (0=blank, 999=null, 1..N=valid)
 * @param electionId  Election ID stored in the contract
 */
function dummyProof(merkleRoot, nullifier, candidateId, electionId) {
  return {
    proof: "0x",
    pubSignals: [BigInt(merkleRoot), BigInt(nullifier), BigInt(candidateId), BigInt(electionId)],
  };
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Using account:", deployer.address);

  const voting = await ethers.getContractAt("VotingContract", VOTING_ADDRESS);

  // ── 1. Create election ──────────────────────────────────────────────────
  console.log("\n1. Creating election...");
  let tx = await voting.createElection(
    "Eleição Acadêmica 2025",
    "Eleição de prova-de-conceito com ZK-SNARKs"
  );
  await tx.wait();
  console.log("   Election created:", await voting.electionName());
  console.log("   Election ID     :", (await voting.currentElectionId()).toString());

  // ── 2. Add candidates ───────────────────────────────────────────────────
  console.log("\n2. Adding candidates...");
  tx = await voting.addCandidate("Alice", "Partido A", 10);
  await tx.wait();
  tx = await voting.addCandidate("Bob", "Partido B", 20);
  await tx.wait();
  console.log("   Candidates added:", (await voting.getCandidateCount()).toString());

  // ── 3. Register voter hashes ────────────────────────────────────────────
  console.log("\n3. Registering voter hashes...");
  const hashes = Array.from({ length: 15 }, (_, i) =>
    BigInt(ethers.keccak256(ethers.toUtf8Bytes(`voter_${i}`)))
  );
  tx = await voting.registerVoterHashes(hashes);
  await tx.wait();
  console.log("   Voter hashes registered:", hashes.length);

  // ── 4. Set Merkle root ──────────────────────────────────────────────────
  console.log("\n4. Setting Merkle root...");
  // In production, compute this from the actual Merkle tree of voter hashes.
  const merkleRoot = BigInt(
    ethers.keccak256(ethers.toUtf8Bytes("merkle_root_placeholder"))
  );
  tx = await voting.setMerkleRoot(merkleRoot);
  await tx.wait();
  console.log("   Merkle root set:", (await voting.voterMerkleRoot()).toString());

  // ── 5. Open election ────────────────────────────────────────────────────
  console.log("\n5. Opening election...");
  tx = await voting.openElection();
  await tx.wait();
  console.log("   Election state:", (await voting.state()).toString()); // 1 = OPEN

  // ── 6. Zerésima (confirm zero votes before first cast) ──────────────────
  console.log("\n6. Zerésima (pre-election audit)...");
  const [zName, zCandidates, zVoters, zTotal, zAllZero] = await voting.getZeresima();
  console.log("   Election name   :", zName);
  console.log("   Candidates      :", zCandidates.toString());
  console.log("   Registered voters:", zVoters.toString());
  console.log("   Total votes so far:", zTotal.toString());
  console.log("   All candidates zero:", zAllZero);

  // ── 7. Cast a vote ──────────────────────────────────────────────────────
  // NOTE: This uses a dummy proof and only works against a MockVerifier.
  //       Replace with a real PLONK proof from snarkjs in production.
  console.log("\n7. Casting vote (dummy proof — MockVerifier only)...");
  const electionId = await voting.currentElectionId();
  const proof = dummyProof(merkleRoot, 12345, 1, electionId); // nullifier=12345, candidateId=1 (Alice)
  tx = await voting.castVote(proof.proof, proof.pubSignals);
  await tx.wait();
  console.log("   Vote cast.");

  // ── 8. Close election ───────────────────────────────────────────────────
  console.log("\n8. Closing election...");
  tx = await voting.closeElection();
  await tx.wait();
  console.log("   Election state:", (await voting.state()).toString()); // 2 = FINISHED

  // ── 9. Get results ──────────────────────────────────────────────────────
  console.log("\n9. Results:");
  const [candidatesResult, blank, nullV, total] = await voting.getResults();
  for (const c of candidatesResult) {
    console.log(
      `   [${c.number}] ${c.name} (${c.party}): ${c.voteCount} vote(s)`
    );
  }
  console.log("   Blank votes :", blank.toString());
  console.log("   Null votes  :", nullV.toString());
  console.log("   Total votes :", total.toString());
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
