#!/usr/bin/env bash
# scripts/sync_circuit_artifacts.sh
#
# Builds the sibling pi-votacao-zk-circuits repo (if needed) and copies the
# four artifacts required for real-mode demo + on-chain verification into
# scripts/artifacts/ and contracts/ respectively.
#
#   scripts/artifacts/voter_proof.wasm        (witness generator)
#   scripts/artifacts/voter_proof.zkey        (PLONK proving key)
#   scripts/artifacts/verification_key.json   (verification key for snarkjs.verify)
#   src/Verifier.sol                          (on-chain Solidity verifier — Foundry layout)
#
# After running this, recompile contracts and run:
#   npm run demo:real
#
# WARNING: this will OVERWRITE src/Verifier.sol.
# Verifier.sol is auto-generated by snarkjs and must NEVER be hand-edited.
# The only post-processing applied is stripping the dead `hardhat/console.sol`
# import that some snarkjs revisions inject — see sed below.

set -euo pipefail

THIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BLOCKCHAIN_ROOT="$(cd "$THIS_DIR/.." && pwd)"
CIRCUITS_REPO="${CIRCUITS_REPO:-$(cd "$BLOCKCHAIN_ROOT/../pi-votacao-zk-circuits" 2>/dev/null && pwd || echo "")}"

if [[ -z "$CIRCUITS_REPO" || ! -d "$CIRCUITS_REPO" ]]; then
  echo "✗ Could not locate pi-votacao-zk-circuits repo." >&2
  echo "  Set CIRCUITS_REPO=/path/to/pi-votacao-zk-circuits and retry." >&2
  exit 1
fi

echo "→ Circuits repo: $CIRCUITS_REPO"
echo "→ Blockchain repo: $BLOCKCHAIN_ROOT"

ARTIFACT_DIR="$BLOCKCHAIN_ROOT/scripts/artifacts"
mkdir -p "$ARTIFACT_DIR"

WASM="$CIRCUITS_REPO/build/voter_proof_js/voter_proof.wasm"
ZKEY="$CIRCUITS_REPO/build/voter_proof.zkey"
VKEY="$CIRCUITS_REPO/build/verification_key.json"
VERIFIER="$CIRCUITS_REPO/build/Verifier.sol"
CHECKSUMS="$CIRCUITS_REPO/build/CHECKSUMS.txt"

if [[ ! -f "$WASM" || ! -f "$ZKEY" || ! -f "$VKEY" || ! -f "$VERIFIER" ]]; then
  echo "→ Build artifacts missing — running 'make' in circuits repo..."
  ( cd "$CIRCUITS_REPO" && make )
fi

for f in "$WASM" "$ZKEY" "$VKEY" "$VERIFIER"; do
  if [[ ! -f "$f" ]]; then
    echo "✗ Build did not produce expected artifact: $f" >&2
    exit 1
  fi
done

# Always (re)generate CHECKSUMS.txt to ensure it reflects the current build.
echo "→ Regenerating circuit-side CHECKSUMS.txt..."
( cd "$CIRCUITS_REPO" && make checksums >/dev/null )
if [[ ! -f "$CHECKSUMS" ]]; then
  echo "✗ Expected checksum file not produced: $CHECKSUMS" >&2
  exit 1
fi

cp "$WASM"      "$ARTIFACT_DIR/voter_proof.wasm"
cp "$ZKEY"      "$ARTIFACT_DIR/voter_proof.zkey"
cp "$VKEY"      "$ARTIFACT_DIR/verification_key.json"
cp "$CHECKSUMS" "$ARTIFACT_DIR/CHECKSUMS.txt"

echo "✓ Copied wasm/zkey/vkey + CHECKSUMS.txt → $ARTIFACT_DIR"

# Verifier.sol — overwrite the on-chain verifier
cp "$VERIFIER" "$BLOCKCHAIN_ROOT/src/Verifier.sol"

# Defence in depth: strip the dead `import "hardhat/console.sol";` line in
# case the upstream circuits-repo patch is missing (e.g. older snarkjs or a
# pre-patch checkout). The line has no runtime effect — it's just unused
# scaffolding that prevents Foundry from compiling.
sed -i '/^import "hardhat\/console\.sol";$/d' "$BLOCKCHAIN_ROOT/src/Verifier.sol"

echo "✓ Copied Verifier.sol → src/Verifier.sol (hardhat/console import stripped if present)"

# Verify provenance immediately so a corrupted sync fails loudly.
echo ""
echo "→ Verifying artifact checksums against circuit-side CHECKSUMS.txt..."
bash "$BLOCKCHAIN_ROOT/scripts/verify_checksums.sh"

echo ""
echo "Next steps:"
echo "  1. forge build"
echo "  2. npm run demo:real    # or: make test-mocha"
